security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$w4JRUDKweW1vXINDdUc0leA8Smen6W8uPs.aDeIcpfOvOwX1d19wi
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
#            logout:
#                path:   /logout
#                target: /cool/stuff
#            http_basic:
#                provider: in_memory
            form_login:
                check_path: security_login
                login_path: security_login
#                csrf_token_generator: security.csrf.token_manage
                default_target_path: admin

            logout:
                path: security_logout
                target: security_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/logout, roles: ROLE_ADMIN }

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
